# Generated by Django 2.0.5 on 2020-08-06 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Project name')),
                ('version', models.CharField(max_length=50, verbose_name='Project version')),
                ('type', models.CharField(choices=[('Web', 'Web'), ('App', 'App')], max_length=50, verbose_name='Project Type')),
                ('description', models.CharField(blank=True, max_length=512, null=True, verbose_name='Project description')),
                ('status', models.BooleanField(default=True, verbose_name='Project status')),
                ('lastUpdateTime', models.DateTimeField(auto_now=True, verbose_name='Last update time')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('owner', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Project',
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='None', max_length=11, verbose_name='phone number'),
        ),
    ]
