# Generated by Django 2.0.5 on 2020-08-13 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0003_auto_20200807_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user',
            new_name='owner',
        ),
    ]
