# Generated by Django 2.0.5 on 2020-08-17 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0005_projectdynamic'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalHost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('host', models.CharField(max_length=256, verbose_name='host地址')),
                ('descriptions', models.CharField(max_length=256, verbose_name='描述')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_test.Project', verbose_name='项目')),
            ],
            options={
                'verbose_name': 'HOST',
                'verbose_name_plural': 'Host管理',
            },
        ),
    ]
