# Generated by Django 2.0.5 on 2020-08-18 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0006_globalhost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalhost',
            old_name='descriptions',
            new_name='description',
        ),
    ]
