# Generated by Django 2.0.5 on 2020-08-24 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_test', '0010_auto_20200821_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIHead',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024, verbose_name='消息头')),
                ('value', models.CharField(blank=True, max_length=1024, null=True, verbose_name='请求值')),
            ],
            options={
                'verbose_name': '请求头',
                'verbose_name_plural': '请求头管理',
            },
        ),
        migrations.CreateModel(
            name='APIInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='接口名称')),
                ('http_type', models.CharField(choices=[('HTTP', 'HTTP'), ('HTTPS', 'HTTPS')], default='HTTP', max_length=50, verbose_name='http/https')),
                ('request_type', models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=50, verbose_name='请求方式')),
                ('api_address', models.CharField(max_length=1024, verbose_name='接口地址')),
                ('request_parameter_type', models.CharField(choices=[('form-data', '表单(form-data)'), ('raw', '源数据（raw）'), ('Restful', 'Restful')], max_length=50, verbose_name='请求参数格式')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('mock_status', models.BooleanField(default=False, verbose_name='mock状态')),
                ('mock_code', models.CharField(blank=True, choices=[('200', '200'), ('302', '302'), ('400', '400'), ('404', '404'), ('500', '500'), ('502', '502')], max_length=50, null=True, verbose_name='Http状态')),
                ('data', models.TextField(blank=True, null=True, verbose_name='Mock内容')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最近更新')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='描述')),
                ('api_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_group', to='api_test.APIGroup', verbose_name='所属分组')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_project', to='api_test.Project', verbose_name='所属项目')),
                ('update_user', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_update_user', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '接口',
                'verbose_name_plural': '接口管理',
            },
        ),
        migrations.CreateModel(
            name='APIParameter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024, verbose_name='参数名')),
                ('_type', models.CharField(choices=[('Int', 'Int'), ('String', 'String')], default='String', max_length=1024, verbose_name='参数类型')),
                ('value', models.CharField(blank=True, max_length=1024, null=True, verbose_name='参数值')),
                ('required', models.BooleanField(default=True, verbose_name='是否必填')),
                ('restrict', models.CharField(blank=True, max_length=1024, null=True, verbose_name='输入限制')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='描述')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_parameters', to='api_test.APIInfo', verbose_name='所属接口')),
            ],
            options={
                'verbose_name': '请求参数',
                'verbose_name_plural': '请求参数管理',
            },
        ),
        migrations.CreateModel(
            name='APIParameterRaw',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('api', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='request_parameter_raw', to='api_test.APIInfo', verbose_name='所属接口')),
            ],
            options={
                'verbose_name': '请求参数Raw',
            },
        ),
        migrations.CreateModel(
            name='APIResponse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024, verbose_name='参数名')),
                ('_type', models.CharField(choices=[('Int', 'Int'), ('String', 'String')], default='String', max_length=1024, verbose_name='参数类型')),
                ('value', models.CharField(blank=True, max_length=1024, null=True, verbose_name='参数值')),
                ('required', models.BooleanField(default=True, verbose_name='是否必含')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='描述')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='api_test.APIInfo', verbose_name='所属接口')),
            ],
            options={
                'verbose_name': '返回参数',
                'verbose_name_plural': '返回参数管理',
            },
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='permission_type',
            field=models.CharField(choices=[('超级管理员', '超级管理员'), ('开发人员', '开发人员'), ('测试人员', '测试人员')], max_length=50, verbose_name='权限角色'),
        ),
        migrations.AddField(
            model_name='apihead',
            name='api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headers', to='api_test.APIInfo', verbose_name='所属接口'),
        ),
    ]
