# Generated by Django 2.0.5 on 2020-10-26 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0013_auto_20200904_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationCaseApi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='接口名称')),
                ('http_type', models.CharField(choices=[('HTTP', 'HTTP'), ('HTTPS', 'HTTPS')], default='HTTP', max_length=50, verbose_name='HTTP/HTTPS')),
                ('request_type', models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=50, verbose_name='请求方式')),
                ('api_address', models.CharField(max_length=1024, verbose_name='接口地址')),
                ('request_parameter_type', models.CharField(choices=[('form-data', '表单(form-data)'), ('raw', '源数据（raw）'), ('Restful', 'Restful')], max_length=50, verbose_name='参数请求格式')),
                ('format_raw', models.BooleanField(default=False, verbose_name='是否转换位源数据')),
                ('examine_type', models.CharField(choices=[('no_check', '不校验'), ('only_check_status', '校验http状态'), ('json', 'JSON校验'), ('entirely_check', '完全校验'), ('regular_check', '正则校验')], default='no_check', max_length=50, verbose_name='校验方式')),
                ('http_code', models.CharField(blank=True, choices=[('0', '0'), ('200', '200'), ('302', '302'), ('400', '400'), ('404', '404'), ('500', '500'), ('502', '502')], max_length=50, null=True, verbose_name='HTTP状态')),
                ('response_code', models.TextField(blank=True, null=True, verbose_name='返回内容')),
                ('automation_test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api', to='api_test.AutomationTestCase', verbose_name='用例')),
            ],
            options={
                'verbose_name': '用例接口',
                'verbose_name_plural': '用例接口管理',
            },
        ),
        migrations.CreateModel(
            name='AutomationHead',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024, verbose_name='参数名')),
                ('value', models.CharField(blank=True, max_length=1024, null=True, verbose_name='内容')),
                ('interrelate', models.BooleanField(default=False, verbose_name='是否关联')),
                ('automation_case_api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='header', to='api_test.AutomationCaseApi', verbose_name='接口')),
            ],
            options={
                'verbose_name': '请求头',
                'verbose_name_plural': '请求头管理',
            },
        ),
        migrations.CreateModel(
            name='AutomationParameter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024, verbose_name='参数名')),
                ('value', models.CharField(blank=True, max_length=1024, null=True, verbose_name='内容')),
                ('interrelate', models.BooleanField(default=False, verbose_name='是否关联')),
                ('automation_case_api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_list', to='api_test.AutomationCaseApi', verbose_name='接口')),
            ],
            options={
                'verbose_name': '接口参数',
                'verbose_name_plural': '接口参数管理',
            },
        ),
        migrations.CreateModel(
            name='AutomationParameterRaw',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.TextField(blank=True, null=True, verbose_name='请求参数源数据')),
                ('automation_case_api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_raw', to='api_test.AutomationCaseApi', verbose_name='接口')),
            ],
            options={
                'verbose_name': '请求参数源数据',
                'verbose_name_plural': '请求参数源数据管理',
            },
        ),
        migrations.CreateModel(
            name='AutomationResponseJson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1024, null=True, verbose_name='JSON参数')),
                ('tier', models.CharField(blank=True, max_length=1024, null=True, verbose_name='层级关系')),
                ('type', models.CharField(choices=[('json', 'json'), ('Regular', 'Regular')], default='json', max_length=1024, verbose_name='关联类型')),
                ('automation_case_api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='api_test.AutomationCaseApi', verbose_name='接口')),
            ],
            options={
                'verbose_name': '结果JSON参数',
                'verbose_name_plural': '结果JSON参数管理',
            },
        ),
        migrations.CreateModel(
            name='AutomationTestResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('automation_case_api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_result', to='api_test.AutomationCaseApi', verbose_name='接口')),
            ],
        ),
    ]
